name: autodeploy
on:
    schedule:
        - cron: '* * * * *'

jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.1
            - id: commit_msg
              name: Get HEAD commit message
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                echo ::set-output name=msg::$(git log -1 --pretty=%s)
            - if: steps.commit_msg.outputs.msg == 'bump'
              name: Amend bump
              run: |
                  git commit --allow-empty --amend --no-edit
                  git push
            - if: steps.commit_msg.outputs.msg != 'bump'
              name: New bump
              run: |
                  git commit --allow-empty -m 'bump'
                  git push

